name: "Create dotenv"
author: "Saurav Sharma"
description: "GitHub Action to create .env file in repository"
branding:
    icon: "terminal"
    color: "blue"
inputs:
    env-prefix:
        description: "Prefix for env file content"
        required: false
        default: ""
    file-name:
        description: "File name for env file"
        required: false
        default: ".env"
    directory:
        description: "Directory for env file"
        required: false
        default: "."
outputs:
    env-file:
        description: "Env file location"
runs:
    using: "node20"
    main: "dist/index.js"
