name: "Create dotenv"
author: "Saurav Sharma"
description: "GitHub Action to create .env file in repository"
branding:
    icon: "terminal"
    color: "blue"
inputs:
    input-prefix:
        description: "Prefix for environment variable"
        required: false
        default: ""
    file-path:
        description: "Full path for env file"
        required: false
        default: ".env"
    output-prefix:
        description: "Prefix for .env file content"
        required: false
        default: ""
    write-mode:
        description: "Mode for writing a file which can be either overwrite mode or read mode"
        required: false
        default: "overwrite"
runs:
    using: "node20"
    main: "dist/index.js"
